In [56]:
a = 123
print(type(a))
print(type(float(a)))


a = True
print(type(a))
print(type(float(a)))


a = "9.99"
print(type(a))
print(type(float(a)))


a = True
print(type(a))
print(type(int(a)))

a = 9.87
print(type(a))
print(type(int(a)))

a = 10000
print(type(a))
print(type(str(a)))

a = 4566
print(type(a))
print(type(bool(a)))


a = "678"
print(type(a))
print(type(int(a)))

a = 99.9
print(type(a))
print(type(str(a)))

a = 89.67
print(type(a))
print(type(bool(a)))

a = "true"
print(type(a))
print(type(bool(a)))

a = True
print(type(a))
print(type(str(a)))

a = "9.76"
print(type(a))
print(type(float(a)))

a = "sanyu"
print(type(a))
print(type(list(a)))

a = (1,2,3,4,5,6,)
print(type(a))
print(type(list(a)))

a = {1,2,3}
print(type(a))
print(type(list(a)))

name = {}
print(type(name))
print(type(list(name)))

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'bool'>
<class 'int'>
<class 'float'>
<class 'int'>
<class 'int'>
<class 'str'>
<class 'int'>
<class 'bool'>
<class 'str'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'float'>
<class 'bool'>
<class 'str'>
<class 'bool'>
<class 'bool'>
<class 'str'>
<class 'str'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'tuple'>
<class 'list'>
<class 'set'>
<class 'list'>
<class 'dict'>
<class 'list'>